apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-auth-runtime-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nexusflow-staging-secrets
  target:
    name: jwt-auth-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: nexusflow/staging/jwt-auth
        property: JWT_SECRET
