apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: nexusflow-staging-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: nexusflow-secrets
      server:
        url: https://kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: default
      auth:
        serviceAccount:
          name: jwt-auth-remote-reader
          namespace: external-secrets
