apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../jwt-auth-lab
  - namespace-seed.yaml
  - seed-secret.yaml
  - serviceaccount-reader.yaml
  - clusterrolebinding-reader.yaml
  - clustersecretstore.yaml
